name: Rector

on: [push, pull_request]

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    # Rector as composer dependency
                    -
                        name: 'Rector Composer - Show With Sets'
                        install: composer install -d .tools/rector --no-progress --ansi
                        run: .tools/rector/vendor/bin/rector show --config rector-with-sets.php --ansi

                    -
                        name: 'Rector Composer - Process'
                        install: composer install -d .tools/rector --no-progress --ansi
                        run: .tools/rector/vendor/bin/rector process --config rector-ci.php --ansi --dry-run

                    # Rector as Prefixed PHAR
                    -
                        name: 'Rector Prefixed - Show With Sets'
                        install: composer install -d .tools/rector-prefixed --no-progress --ansi
                        run: .tools/rector-prefixed/vendor/bin/rector show --config rector-with-sets.php --ansi

                    -
                        name: 'Rector Prefixed - Process'
                        install: composer install -d .tools/rector-prefixed --no-progress --ansi
                        run: .tools/rector-prefixed/vendor/bin/rector process --config rector-ci.php --ansi --dry-run

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ${{ matrix.actions.install }}

            # load local classes
            -   run: composer dump-autoload

            -   run: ${{ matrix.actions.run }}
