name: Rector CI

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    -
        name: Rector CI

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install -d .tools/rector --no-progress --ansi

            # load local classes
            -   run: composer dump-autoload

            # run rector
            -   run: composer rector-ci
